[parity]
chain = "config/spec.json"
base_path = "/opt/parity"
[network]
port = 30300
reserved_peers = "bootnodes.txt"
nat = "extip:52.183.16.194"
[ipc]
disable = false
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "secretstore", "pubsub"]
[rpc]
port = 8540
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
interface = "all"
cors = ["all"]
[ui]
port = 8180
[websockets]
port = 8546
[account]
password = ["node.pwd"]
[mining]
engine_signer = "0x00a67cc5f959ec35d78d72149a3078acb22a4c09"
reseal_on_txs = "none"
force_sealing = true
